name: CD - Deploy Monitoring Stack to GCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: observabilidade-ci   # 🔒 Nome do seu environment

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      INSTANCE_NAME: ${{ secrets.GCE_INSTANCE }}
      ZONE: ${{ secrets.GCE_ZONE }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          # Caso use chave de conta de serviço:
          # credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy via SSH
        run: |
          gcloud compute ssh ${{ env.INSTANCE_NAME }} \
            --zone ${{ env.ZONE }} \
            --command '
              set -e
              cd Raijimobi-observabilidade-grafana
              git pull origin main
              docker compose down -v
              docker compose pull
              docker compose up -d
            '